export default {
  adopt: require("./adopt.png"),
  cat: require("./cat.png"),
  dog: require("./dog.png"),
  missing: require("./missing.png"),
  noAdoption: require("./noAdoption.png"),
  noMissing: require("./noMissing.jpeg"),
  noMissing: require("./noMissing.png"),
  noWish: require("./noWish.jpeg"),
  parrot: require("./parrot.jpeg"),
  pets: require("./pets.jpeg"),
  rabbit: require("./rabbit.jpeg"),
  turtle: require("./turtle.png"),
  wish: require("./wish.png"),
};
