create table "public"."Contact Us" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "contact" text not null,
    "name" text not null,
    "message" character varying not null
);


CREATE UNIQUE INDEX "Contact Us_pkey" ON public."Contact Us" USING btree (id);

alter table "public"."Contact Us" add constraint "Contact Us_pkey" PRIMARY KEY using index "Contact Us_pkey";


