
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."Adoption" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "image" character varying,
    "description" character varying,
    "type" "text" NOT NULL,
    "contact" "text" NOT NULL,
    "pet_name" "text"
);

ALTER TABLE "public"."Adoption" OWNER TO "postgres";

ALTER TABLE "public"."Adoption" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Adoption_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Missing" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "image" character varying,
    "description" character varying NOT NULL,
    "type" "text" NOT NULL
);

ALTER TABLE "public"."Missing" OWNER TO "postgres";

ALTER TABLE "public"."Missing" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Missing_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Wish" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "description" character varying NOT NULL,
    "name" "text" NOT NULL,
    "contact" "text",
    "type" "text" NOT NULL
);

ALTER TABLE "public"."Wish" OWNER TO "postgres";

ALTER TABLE "public"."Wish" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Wish_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."Adoption"
    ADD CONSTRAINT "Adoption_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Missing"
    ADD CONSTRAINT "Missing_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Wish"
    ADD CONSTRAINT "Wish_pkey" PRIMARY KEY ("id");

REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."Adoption" TO "anon";
GRANT ALL ON TABLE "public"."Adoption" TO "authenticated";
GRANT ALL ON TABLE "public"."Adoption" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Adoption_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Adoption_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Adoption_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Missing" TO "anon";
GRANT ALL ON TABLE "public"."Missing" TO "authenticated";
GRANT ALL ON TABLE "public"."Missing" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Missing_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Missing_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Missing_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Wish" TO "anon";
GRANT ALL ON TABLE "public"."Wish" TO "authenticated";
GRANT ALL ON TABLE "public"."Wish" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Wish_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Wish_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Wish_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
